services:
  mysql-backup:
    container_name: mysql-backup-prod
    env_file: .env.prod
    volumes:
      - ${HDD_MOUNT_PATH:-./backups-hdd}:/backups-hdd
      - ./servers.prod.json:/config/servers.json:ro
