#!/usr/bin/env bash
set -euo pipefail

# ─── Load .env ───────────────────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${SCRIPT_DIR}/.env"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "[ERROR] .env file not found at: $ENV_FILE"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

MINIO_ROOT_USER="${MINIO_ROOT_USER:-minioadmin}"
MINIO_ROOT_PASSWORD="${MINIO_ROOT_PASSWORD:-minioadmin}"
MINIO_API_PORT="${MINIO_API_PORT:-9000}"
MINIO_HOST="http://localhost:${MINIO_API_PORT}"

# ─── Args ─────────────────────────────────────────────────────────────────────
USERNAME="${1:-}"

if [[ -z "$USERNAME" ]]; then
  echo "Usage: $0 <username> [description]"
  echo "Example: $0 myapp 'Access key for myapp service'"
  exit 1
fi

DESCRIPTION="${2:-Generated by generate-accesskey.sh on $(date '+%Y-%m-%d %H:%M:%S')}"

# ─── Check mc available ───────────────────────────────────────────────────────
if ! command -v mc &>/dev/null; then
  echo "[INFO] mc not found locally, using Docker..."
  USE_DOCKER=true
else
  USE_DOCKER=false
fi

mc_cmd() {
  if [[ "$USE_DOCKER" == true ]]; then
    docker exec minio mc "$@"
  else
    mc "$@"
  fi
}

# ─── Set alias ────────────────────────────────────────────────────────────────
echo "[INFO] Connecting to MinIO at $MINIO_HOST..."
mc_cmd alias set local "$MINIO_HOST" "$MINIO_ROOT_USER" "$MINIO_ROOT_PASSWORD" --api S3v4 > /dev/null

# ─── Check user exists ────────────────────────────────────────────────────────
if ! mc_cmd admin user info local "$USERNAME" &>/dev/null; then
  echo "[ERROR] User '$USERNAME' does not exist in MinIO."
  echo "        Create it first: mc admin user add local $USERNAME <password>"
  exit 1
fi

# ─── Generate access key ──────────────────────────────────────────────────────
echo "[INFO] Generating access key for user: $USERNAME"

RAW_OUTPUT=$(mc_cmd admin accesskey create local "$USERNAME" \
  --comment "$DESCRIPTION" \
  --json 2>/dev/null)

ACCESS_KEY=$(echo "$RAW_OUTPUT" | grep -o '"accessKey":"[^"]*"' | cut -d'"' -f4)
SECRET_KEY=$(echo "$RAW_OUTPUT" | grep -o '"secretKey":"[^"]*"' | cut -d'"' -f4)

if [[ -z "$ACCESS_KEY" || -z "$SECRET_KEY" ]]; then
  echo "[ERROR] Failed to generate access key. Raw output:"
  echo "$RAW_OUTPUT"
  exit 1
fi

# ─── Output ───────────────────────────────────────────────────────────────────
OUTPUT_FILE="${SCRIPT_DIR}/accesskey-${USERNAME}-$(date '+%Y%m%d%H%M%S').txt"

cat <<EOF | tee "$OUTPUT_FILE"

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  MinIO Access Key Generated
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  User        : $USERNAME
  Description : $DESCRIPTION
  Access Key  : $ACCESS_KEY
  Secret Key  : $SECRET_KEY
  Endpoint    : $MINIO_HOST
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  Saved to: $OUTPUT_FILE
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

EOF

echo "[WARN] Keep this file secure and do not commit it to version control."